export const services = [
    {
        id: 1,
        title: "Промышленная сварка труб",
        description: "Сварка под высоким давлением с контролем качества по стандартам ASME/ГОСТ.",
        price: "от 5000 ₽ / стык",
        image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=2070&auto=format&fit=crop",
        features: ["Рентген-контроль", "Сертифицированные материалы", "Работа в сжатые сроки"],
        category: "Промышленность",
    },
    {
        id: 2,
        title: "Монтаж металлоконструкций",
        description: "Изготовление и установка балок, ферм и каркасов для зданий.",
        price: "от 45000 ₽ / тонна",
        image: "https://images.unsplash.com/photo-1542466034-099525c317ac?q=80&w=1974&auto=format&fit=crop",
        features: ["Проектирование", "Высотные работы", "Антикоррозийная обработка"],
        category: "Строительство",
    },
    {
        id: 3,
        title: "Сварка TIG (Аргон)",
        description: "Точная сварка нержавеющей стали и алюминия для пищевой и хим. промышленности.",
        price: "от 3000 ₽ / час",
        image: "https://images.unsplash.com/photo-1565610220671-5544439c0f09?q=80&w=1964&auto=format&fit=crop",
        features: ["Идеальный шов", "Без брызг", "Тонколистовой металл"],
        category: "Точная работа",
    },
    {
        id: 4,
        title: "Ремонт спецтехники",
        description: "Восстановление ковшей, стрел и рам тяжелой техники.",
        price: "от 10000 ₽",
        image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?q=80&w=2070&auto=format&fit=crop",
        features: ["Наплавка", "Усиление узлов", "Выезд на объект"],
        category: "Ремонт",
    },
    {
        id: 5,
        title: "Художественная ковка",
        description: "Изготовление ворот, заборов и перил по индивидуальным эскизам.",
        price: "по запросу",
        image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=2070&auto=format&fit=crop",
        features: ["Уникальный дизайн", "Порошковая покраска", "Долговечность"],
        category: "Частные заказы",
    },
    {
        id: 6,
        title: "Аварийный выезд",
        description: "Срочный ремонт прорывов и поломок 24/7.",
        price: "от 5000 ₽ выезд",
        image: "https://plus.unsplash.com/premium_photo-1664302152996-33924376c989?q=80&w=2070&auto=format&fit=crop",
        features: ["Прибытие за 2 часа", "Полный комплект оборудования", "Гарантия"],
        category: "Сервис",
    },
];
